### ISSUE TITLE
Question: Can this be used to generate license keys that expire?

### ISSUE THREAD

**Issue by omarojo** [jedisct1/swift-sodium#111]
Im making a framework library, and I wanna add license capabilities. So I give my clients a license key that expire on certain date. So maybe I can generate the license key with sodium?

Im thinking encrypting a date "2017-12-16" + a bundle id "com.company.myapp" to generate the license key, ex. "xxxxxxxxxxx"  then in my framework internally I decrypt it and compare the date to the current date and the bundle id with the current one. 

but I wonder if the generate key would be a huge string or a short one.. like most SDKs use.

I would love any suggestion. :) thank you

**Comment by jedisct1** [comment]
If something is encrypted, but the key is present and persistent on the same device, it's equivalent to having no encryption at all.

Presumably, what you want to achieve is:
- Prevent the date from being modified via a non-encrypted backup (even though there are becoming rare)
- Prevent a MITM proxy or a fake license server from responding to the initial license request with an arbitrary date.

The date doesn't need to be encrypted, or even authenticated, but it should be stored in the secure enclave. So, on iOS, the keychain is your friend.

In order to prevent a local proxy from impersonating the license server, you need to check that the server certificate has been signed with your own CA, for example with `ServerTrustPolicyManager` if you are using Alamofire.
