### ISSUE TITLE
Where is sodium.pwHash.scrypt.hash()

### ISSUE THREAD

**Issue by WANGjieJacques** [jedisct1/swift-sodium#116]
Hi @jedisct1, I use `sodium.pwHash.scrypt.hash` of the previous version of sodium, today I update to the last version of sodium, the class scrypt doesn't exist any more. what can I do for this ?

**Comment by jedisct1** [comment]
Hi!

scrypt was a stopgap until a high-level API for password hashing was defined. It was only available as a low-level APIs, and wasn't used by anything else.

It was removed a long time ago from minimal builds of libsodium, since other algorithms were chosen for the high-level password hashing API.

swift-sodium tries to only expose high-level APIs, that will remain supported for a long time, and embeds minimal builds of libsodium to ensure that this is the case.

**Comment by WANGjieJacques** [comment]
thanks, @jedisct1 , but what is the high-level API for scrypt ?

**Comment by jedisct1** [comment]
There is none. There are no more implementations of scrypt in the bundled library.

In order to hash passwords, you should simply use `sodium.pwHash`, which isn't tied to a specific algorithm, but will automatically use the best one available for the current version of the library.

**Comment by markshiz** [comment]
I will also second, from a library consumer perspective, this is pretty annoying situation.  One of the reasons we used this library was that it provided a cross platform approach to encryption.  We are using `RbNaCl` on our backend, which has a Scrypt implementation.  Now that we are forced to update this library due to Xcode 10.2, I have no upgrade path.  I need to support these functions because our app needs to be backwards compatible with the website.
