### ISSUE TITLE
Bitcode supported

### ISSUE THREAD

**Issue by icodesign** [jedisct1/swift-sodium#14]

**Comment by jedisct1** [comment]
?

**Comment by iCodesign** [comment]
Bitcode is introduced in Xcode 7, see reference http://stackoverflow.com/questions/30722606/what-does-enable-bitcode-do-in-xcode-7

**Comment by jedisct1** [comment]
I'm not sure this is a good idea: https://medium.com/@FredericJacobs/why-i-m-not-enabling-bitcode-f35cd8fbfcc5

**Comment by iCodesign** [comment]
But as a library, do you think that we should leave the choices to developers? Once someone imports this framework, he will need to disable bitcode for the whole project which he may not want to.

**Comment by blochberger** [comment]
Although I'm not opting for bitcode support I think it's worth explicitly mentioning the following here:

> **Note:** For iOS apps, bitcode is the default, but optional. For watchOS and tvOS apps, bitcode is required. If you provide bitcode, all apps and frameworks in the app bundle (all targets in the project) need to include bitcode. [[App Distribution Guide](https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html#//apple_ref/doc/uid/TP40012582-CH35-SW2)]

So for being able to use this framework for developing watchOS or tvOS applications you would actually need bitcode support.

**Comment by jedisct1** [comment]
So, what would it take to add bitcode support, in addition to enabling it in the bindings?

Just compile the libsodium iOS libraries with `-fembed-bitcode`? Does that have to be done for all architectures?

**Comment by sdduursma** [comment]
What is the state of this issue? We recently added swift-sodium to our project that has bitcode enabled so this functionality is important to us. I'd be happy to add bitcode support to swift-sodium.

**Comment by jedisct1** [comment]
In the Swift bindings, I guess it's as easy as setting `ENABLE_BITCODE = YES` for the iOS targets.
Regarding the library itself, what changes have to be made to the `ios.sh` (and possibly `osx.sh`) script? Just add `-fembed-bitcode`? To which targets?

**Comment by sdduursma** [comment]
I enabled Bitcode for the Sodium_iOS target and was able to successfully archive and validate our project without making any changes to `ios.sh`. Is it even necessary to make any changes to `ios.sh`?

**Comment by jedisct1** [comment]
Sounds weird to be able to validate something where parts of the code don't contain any bitcode.

Swift-Sodium had Bitcode enabled, but that was [explicitly disabled](https://github.com/jedisct1/swift-sodium/pull/11#commitcomment-13370173) because of this inconsistency.

**Comment by sdduursma** [comment]
@jedisct1 I was also able to successfully archive the Example iOS target in swift-sodium:

1. (replace `println` with `print`)
2. Enable Bitcode for Release on the Example iOS target. If you archive Example iOS now, it will fail and complain that the Sodium framework does not contain Bitcode.
3. Enable Bitcode for Release on the Sodium_iOS target
4. Archive Example iOS. The archive will succeed without issues.

I also find it weird that the archive succeeds while the static libsodium library doesn't contain Bitcode. However, if it is necessary to add Bitcode to the static libsodium library, it would be nice to create a situation where something fails if it's not added, so we know what needs to be fixed.

I recall that when our team submitted a version of our app for review the first time after Bitcode was introduced to Xcode, we received an email from Apple about issues with our submitted build. It turned out that the issue had to do with Bitcode ([This SO post](http://stackoverflow.com/questions/32526526/invalid-swift-support-files-don-t-match) helped us resolve the issue).

I wonder whether even though archiving a project without adding Bitcode to the static libsodium library seems to work, a build may fail to be submitted to the App Store.

**Comment by jedisct1** [comment]
Bitcode is now enabled, even though the fact that it works without libsodium itself being compiled with Bitcode remains very suspicious.
