### ISSUE TITLE
Cannot archive when creating App with WatchOS-extension

### ISSUE THREAD

**Issue by akbsteam** [jedisct1/swift-sodium#239]
This could definitely be a misunderstanding on my part but ... 

I am trying to use swift-sodium as a dependency for an SPM package which in turn is a dependency of my app, which has an iOS part and a WatchOS extension companion app. It will build and run correctly but not archive.

the Dependencies import in the Package.swift looks like this ... 

```
.package(name: "Sodium", url: "https://github.com/jedisct1/swift-sodium.git", .upToNextMinor(from: "0.9.0")),
```

Compiling Sodium gives me:

```
...../SourcePackages/checkouts/swift-sodium/Sodium/Aead.swift:2:8: error: no such module 'Clibsodium'
import Clibsodium
       ^
```

Similarly, if I create a new project and add a package dependency of swift-sodium as per the README, with just an iOS app, importing Sodium; it works fine. Then I add a WatchOS extension app, and add Clibsodium and Sodium to "Frameworks, Libraries and Embedded Content" in the extension, then I get the same `no such module 'Clibsodium'` error when archiving (it succeeds when just doing a normal build).

Any pointers would be gratefully received!

**Comment by akbsteam** [comment]
Update; tried this PR:-

https://github.com/jedisct1/swift-sodium/pull/235

works for me :D

**Comment by akbsteam** [comment]
Hmm, maybe I spoke too soon. It seems like I can't submit it

**Comment by bas-d** [comment]
Try this: https://github.com/jedisct1/swift-sodium/issues/226#issuecomment-765258545, I think it's the same SPM bug that causes this.

**Comment by akbsteam** [comment]
@bas-d Thanks, that worked a treat.

**Comment by Turacbey** [comment]
It didn't work for me. I still get same error on my Watch extension.
@akbsteam did you change any code on @bas-d 's mentioned ?
By the way, watchOS deployment target is 7.0

**Comment by FabioTacke** [comment]
This is weird. I followed the instructions of your minimal example, @akbsteam. I created a new iOS project, added swift-sodium as dependency (building and archiving succeeded) and then added the watch app extension and it's dependency on Sodium and Clibsodium. I could still build and archive the app successfully.

However archiving fails when using a dependency which depends on swift-sodium instead of adding swift-sodium as a dependency directly. And I experience this behavior independently from an app extension. The iOS project itself is enough to fail the archiving step. (See https://github.com/jedisct1/swift-sodium/issues/226#issuecomment-797509220)
