### ISSUE TITLE
Box, SecretBox implementation.

### ISSUE THREAD

**Issue by WANGjieJacques** [jedisct1/swift-sodium#67]
I found that `Box` only implements `crypto_box`, but no implementation for `crypto_box_curve25519xchacha20poly1305` and `crypto_box_curve25519xsalsa20poly1305`, 
and `SecretBox` only implement `crypto_secretbox`, but no `crypto_secretbox_xsalsa20poly1305` and `crypto_secretbox_xchacha20poly1305`.
I would like to create a pull request for all these `crypto_box_curve25519xchacha20poly1305`, `crypto_box_curve25519xsalsa20poly1305`, `crypto_secretbox_xsalsa20poly1305`, `crypto_secretbox_xchacha20poly1305`, but I don't know the relationship between these `box` or `secretbox`, should I create new classes like `XChaChaBox`, `XSalsaBox`, `XSalsaSecretBox`, `XChachaSecretBox` for these implementations or I can add them to `Box`, `SecretBox` directly.

**Comment by WANGjieJacques** [comment]
it seems all these `Box`, `SecretBox` stuff are the same thing ?

**Comment by jedisct1** [comment]
Usually, you just want to call the high-level API, i.e. `crypto_box`, `crypto_aead` or `crypto_secretbox`, in order to perform an operation.

`crypto_box` is guaranteed to be `curve25519xsalsa20poly1305`, so it's not really useful to have a duplicate class.
While ChaCha20 is interesting as part of an AEAD for interoperability with other libraries, this is not the case for `box` and `secretbox`. XSalsa20 already provides a 192-bit nonce, and there are usually no practical advantages in using ChaCha20 over it.
Unless you really have a use case that requires XChaChaBox, maybe it's better to keep the API minimal and less confusing.

**Comment by WANGjieJacques** [comment]
I see, thanks. @jedisct1
